/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl.impl;

import lab.buaa.software.lidl.lidl.InterfaceElement;
import lab.buaa.software.lidl.lidl.LidlPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Interface Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InterfaceElementImpl extends LidlSymbolImpl implements InterfaceElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InterfaceElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LidlPackage.Literals.INTERFACE_ELEMENT;
  }

} //InterfaceElementImpl
