/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl.impl;

import lab.buaa.software.lidl.lidl.AtomInterfaceType;
import lab.buaa.software.lidl.lidl.AtomInterfaceTypeElement;
import lab.buaa.software.lidl.lidl.CallPart;
import lab.buaa.software.lidl.lidl.CompositeDataType;
import lab.buaa.software.lidl.lidl.CompositeDataTypeElement;
import lab.buaa.software.lidl.lidl.CompositeInterfaceType;
import lab.buaa.software.lidl.lidl.CompositeInterfaceTypeElement;
import lab.buaa.software.lidl.lidl.DataDirection;
import lab.buaa.software.lidl.lidl.IDPart;
import lab.buaa.software.lidl.lidl.InterfaceElement;
import lab.buaa.software.lidl.lidl.LidlArrayItem;
import lab.buaa.software.lidl.lidl.LidlAvtivationConstant;
import lab.buaa.software.lidl.lidl.LidlBoolConstant;
import lab.buaa.software.lidl.lidl.LidlCallExpression;
import lab.buaa.software.lidl.lidl.LidlComposition;
import lab.buaa.software.lidl.lidl.LidlCompositionElement;
import lab.buaa.software.lidl.lidl.LidlData;
import lab.buaa.software.lidl.lidl.LidlDataType;
import lab.buaa.software.lidl.lidl.LidlDefinition;
import lab.buaa.software.lidl.lidl.LidlExpression;
import lab.buaa.software.lidl.lidl.LidlExpresson;
import lab.buaa.software.lidl.lidl.LidlFactory;
import lab.buaa.software.lidl.lidl.LidlImport;
import lab.buaa.software.lidl.lidl.LidlInteraction;
import lab.buaa.software.lidl.lidl.LidlInteractionID;
import lab.buaa.software.lidl.lidl.LidlInterface;
import lab.buaa.software.lidl.lidl.LidlInterfaceType;
import lab.buaa.software.lidl.lidl.LidlNumberConstant;
import lab.buaa.software.lidl.lidl.LidlPackage;
import lab.buaa.software.lidl.lidl.LidlParameter;
import lab.buaa.software.lidl.lidl.LidlProgram;
import lab.buaa.software.lidl.lidl.LidlStringConstant;
import lab.buaa.software.lidl.lidl.LidlSymbol;
import lab.buaa.software.lidl.lidl.LidlText;
import lab.buaa.software.lidl.lidl.ParamCallPart;
import lab.buaa.software.lidl.lidl.RefDataType;
import lab.buaa.software.lidl.lidl.RefDataTypeElement;
import lab.buaa.software.lidl.lidl.RefInterfaceType;
import lab.buaa.software.lidl.lidl.RefInterfaceTypeElement;
import lab.buaa.software.lidl.lidl.TextCallPart;
import lab.buaa.software.lidl.lidl.TypeElement;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class LidlPackageImpl extends EPackageImpl implements LidlPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlProgramEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlImportEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlDefinitionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlDataEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlDataTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass typeElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlInterfaceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlInterfaceTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass interfaceElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlInteractionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlInteractionIDEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass idPartEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlExpressonEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass callPartEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlArrayItemEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlSymbolEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlCompositionElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass compositeDataTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass refDataTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass compositeDataTypeElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass refDataTypeElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atomInterfaceTypeElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass compositeInterfaceTypeElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass refInterfaceTypeElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atomInterfaceTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass compositeInterfaceTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass refInterfaceTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlParameterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlTextEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlCallExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass textCallPartEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass paramCallPartEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlStringConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlNumberConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlBoolConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlAvtivationConstantEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass lidlCompositionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum dataDirectionEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see lab.buaa.software.lidl.lidl.LidlPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private LidlPackageImpl()
  {
    super(eNS_URI, LidlFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link LidlPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static LidlPackage init()
  {
    if (isInited) return (LidlPackage)EPackage.Registry.INSTANCE.getEPackage(LidlPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredLidlPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    LidlPackageImpl theLidlPackage = registeredLidlPackage instanceof LidlPackageImpl ? (LidlPackageImpl)registeredLidlPackage : new LidlPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theLidlPackage.createPackageContents();

    // Initialize created meta-data
    theLidlPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theLidlPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(LidlPackage.eNS_URI, theLidlPackage);
    return theLidlPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlProgram()
  {
    return lidlProgramEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlProgram_Pack()
  {
    return (EAttribute)lidlProgramEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlProgram_Name()
  {
    return (EAttribute)lidlProgramEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlProgram_Imports()
  {
    return (EReference)lidlProgramEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlProgram_Definitions()
  {
    return (EReference)lidlProgramEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlImport()
  {
    return lidlImportEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlImport_ImportedNamespace()
  {
    return (EAttribute)lidlImportEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlDefinition()
  {
    return lidlDefinitionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlDefinition_Nested()
  {
    return (EAttribute)lidlDefinitionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlData()
  {
    return lidlDataEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlData_Name()
  {
    return (EAttribute)lidlDataEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlData_NestedDef()
  {
    return (EReference)lidlDataEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlData_Definition()
  {
    return (EReference)lidlDataEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlData_Defined()
  {
    return (EAttribute)lidlDataEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlDataType()
  {
    return lidlDataTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlDataType_Items()
  {
    return (EReference)lidlDataTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTypeElement()
  {
    return typeElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTypeElement_IsArray()
  {
    return (EAttribute)typeElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTypeElement_Type()
  {
    return (EReference)typeElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlInterface()
  {
    return lidlInterfaceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlInterface_Name()
  {
    return (EAttribute)lidlInterfaceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlInterface_NestedDef()
  {
    return (EReference)lidlInterfaceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlInterface_Definition()
  {
    return (EReference)lidlInterfaceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlInterface_Defined()
  {
    return (EAttribute)lidlInterfaceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlInterfaceType()
  {
    return lidlInterfaceTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlInterfaceType_Conjugate()
  {
    return (EAttribute)lidlInterfaceTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInterfaceElement()
  {
    return interfaceElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlInteraction()
  {
    return lidlInteractionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlInteraction_Id()
  {
    return (EReference)lidlInteractionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlInteraction_Interface()
  {
    return (EReference)lidlInteractionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlInteraction_NestedDef()
  {
    return (EReference)lidlInteractionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlInteraction_Definition()
  {
    return (EReference)lidlInteractionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlInteractionID()
  {
    return lidlInteractionIDEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlInteractionID_Items()
  {
    return (EReference)lidlInteractionIDEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIDPart()
  {
    return idPartEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlExpresson()
  {
    return lidlExpressonEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlExpression()
  {
    return lidlExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlExpression_Item()
  {
    return (EReference)lidlExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlExpression_Items()
  {
    return (EReference)lidlExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCallPart()
  {
    return callPartEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlArrayItem()
  {
    return lidlArrayItemEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlArrayItem_Value()
  {
    return (EReference)lidlArrayItemEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlSymbol()
  {
    return lidlSymbolEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlCompositionElement()
  {
    return lidlCompositionElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlCompositionElement_Param()
  {
    return (EAttribute)lidlCompositionElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlCompositionElement_Value()
  {
    return (EReference)lidlCompositionElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCompositeDataType()
  {
    return compositeDataTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRefDataType()
  {
    return refDataTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCompositeDataTypeElement()
  {
    return compositeDataTypeElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCompositeDataTypeElement_Name()
  {
    return (EAttribute)compositeDataTypeElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRefDataTypeElement()
  {
    return refDataTypeElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAtomInterfaceTypeElement()
  {
    return atomInterfaceTypeElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAtomInterfaceTypeElement_Type()
  {
    return (EReference)atomInterfaceTypeElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAtomInterfaceTypeElement_Direction()
  {
    return (EAttribute)atomInterfaceTypeElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCompositeInterfaceTypeElement()
  {
    return compositeInterfaceTypeElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCompositeInterfaceTypeElement_Name()
  {
    return (EAttribute)compositeInterfaceTypeElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCompositeInterfaceTypeElement_Type()
  {
    return (EReference)compositeInterfaceTypeElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCompositeInterfaceTypeElement_Direction()
  {
    return (EAttribute)compositeInterfaceTypeElementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRefInterfaceTypeElement()
  {
    return refInterfaceTypeElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRefInterfaceTypeElement_Type()
  {
    return (EReference)refInterfaceTypeElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAtomInterfaceType()
  {
    return atomInterfaceTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAtomInterfaceType_Items()
  {
    return (EReference)atomInterfaceTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCompositeInterfaceType()
  {
    return compositeInterfaceTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCompositeInterfaceType_Items()
  {
    return (EReference)compositeInterfaceTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRefInterfaceType()
  {
    return refInterfaceTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRefInterfaceType_Items()
  {
    return (EReference)refInterfaceTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlParameter()
  {
    return lidlParameterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlParameter_Name()
  {
    return (EAttribute)lidlParameterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlParameter_Interface()
  {
    return (EReference)lidlParameterEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlText()
  {
    return lidlTextEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlText_Text()
  {
    return (EAttribute)lidlTextEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlCallExpression()
  {
    return lidlCallExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTextCallPart()
  {
    return textCallPartEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTextCallPart_Text()
  {
    return (EAttribute)textCallPartEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getParamCallPart()
  {
    return paramCallPartEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getParamCallPart_Param()
  {
    return (EReference)paramCallPartEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlStringConstant()
  {
    return lidlStringConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlStringConstant_Value()
  {
    return (EAttribute)lidlStringConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlNumberConstant()
  {
    return lidlNumberConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlNumberConstant_Value()
  {
    return (EAttribute)lidlNumberConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlBoolConstant()
  {
    return lidlBoolConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlBoolConstant_Value()
  {
    return (EAttribute)lidlBoolConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlAvtivationConstant()
  {
    return lidlAvtivationConstantEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLidlAvtivationConstant_Value()
  {
    return (EAttribute)lidlAvtivationConstantEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLidlComposition()
  {
    return lidlCompositionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLidlComposition_Body()
  {
    return (EReference)lidlCompositionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getDataDirection()
  {
    return dataDirectionEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LidlFactory getLidlFactory()
  {
    return (LidlFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    lidlProgramEClass = createEClass(LIDL_PROGRAM);
    createEAttribute(lidlProgramEClass, LIDL_PROGRAM__PACK);
    createEAttribute(lidlProgramEClass, LIDL_PROGRAM__NAME);
    createEReference(lidlProgramEClass, LIDL_PROGRAM__IMPORTS);
    createEReference(lidlProgramEClass, LIDL_PROGRAM__DEFINITIONS);

    lidlImportEClass = createEClass(LIDL_IMPORT);
    createEAttribute(lidlImportEClass, LIDL_IMPORT__IMPORTED_NAMESPACE);

    lidlDefinitionEClass = createEClass(LIDL_DEFINITION);
    createEAttribute(lidlDefinitionEClass, LIDL_DEFINITION__NESTED);

    lidlDataEClass = createEClass(LIDL_DATA);
    createEAttribute(lidlDataEClass, LIDL_DATA__NAME);
    createEReference(lidlDataEClass, LIDL_DATA__NESTED_DEF);
    createEReference(lidlDataEClass, LIDL_DATA__DEFINITION);
    createEAttribute(lidlDataEClass, LIDL_DATA__DEFINED);

    lidlDataTypeEClass = createEClass(LIDL_DATA_TYPE);
    createEReference(lidlDataTypeEClass, LIDL_DATA_TYPE__ITEMS);

    typeElementEClass = createEClass(TYPE_ELEMENT);
    createEAttribute(typeElementEClass, TYPE_ELEMENT__IS_ARRAY);
    createEReference(typeElementEClass, TYPE_ELEMENT__TYPE);

    lidlInterfaceEClass = createEClass(LIDL_INTERFACE);
    createEAttribute(lidlInterfaceEClass, LIDL_INTERFACE__NAME);
    createEReference(lidlInterfaceEClass, LIDL_INTERFACE__NESTED_DEF);
    createEReference(lidlInterfaceEClass, LIDL_INTERFACE__DEFINITION);
    createEAttribute(lidlInterfaceEClass, LIDL_INTERFACE__DEFINED);

    lidlInterfaceTypeEClass = createEClass(LIDL_INTERFACE_TYPE);
    createEAttribute(lidlInterfaceTypeEClass, LIDL_INTERFACE_TYPE__CONJUGATE);

    interfaceElementEClass = createEClass(INTERFACE_ELEMENT);

    lidlInteractionEClass = createEClass(LIDL_INTERACTION);
    createEReference(lidlInteractionEClass, LIDL_INTERACTION__ID);
    createEReference(lidlInteractionEClass, LIDL_INTERACTION__INTERFACE);
    createEReference(lidlInteractionEClass, LIDL_INTERACTION__NESTED_DEF);
    createEReference(lidlInteractionEClass, LIDL_INTERACTION__DEFINITION);

    lidlInteractionIDEClass = createEClass(LIDL_INTERACTION_ID);
    createEReference(lidlInteractionIDEClass, LIDL_INTERACTION_ID__ITEMS);

    idPartEClass = createEClass(ID_PART);

    lidlExpressonEClass = createEClass(LIDL_EXPRESSON);

    lidlExpressionEClass = createEClass(LIDL_EXPRESSION);
    createEReference(lidlExpressionEClass, LIDL_EXPRESSION__ITEM);
    createEReference(lidlExpressionEClass, LIDL_EXPRESSION__ITEMS);

    callPartEClass = createEClass(CALL_PART);

    lidlArrayItemEClass = createEClass(LIDL_ARRAY_ITEM);
    createEReference(lidlArrayItemEClass, LIDL_ARRAY_ITEM__VALUE);

    lidlSymbolEClass = createEClass(LIDL_SYMBOL);

    lidlCompositionElementEClass = createEClass(LIDL_COMPOSITION_ELEMENT);
    createEAttribute(lidlCompositionElementEClass, LIDL_COMPOSITION_ELEMENT__PARAM);
    createEReference(lidlCompositionElementEClass, LIDL_COMPOSITION_ELEMENT__VALUE);

    compositeDataTypeEClass = createEClass(COMPOSITE_DATA_TYPE);

    refDataTypeEClass = createEClass(REF_DATA_TYPE);

    compositeDataTypeElementEClass = createEClass(COMPOSITE_DATA_TYPE_ELEMENT);
    createEAttribute(compositeDataTypeElementEClass, COMPOSITE_DATA_TYPE_ELEMENT__NAME);

    refDataTypeElementEClass = createEClass(REF_DATA_TYPE_ELEMENT);

    atomInterfaceTypeElementEClass = createEClass(ATOM_INTERFACE_TYPE_ELEMENT);
    createEReference(atomInterfaceTypeElementEClass, ATOM_INTERFACE_TYPE_ELEMENT__TYPE);
    createEAttribute(atomInterfaceTypeElementEClass, ATOM_INTERFACE_TYPE_ELEMENT__DIRECTION);

    compositeInterfaceTypeElementEClass = createEClass(COMPOSITE_INTERFACE_TYPE_ELEMENT);
    createEAttribute(compositeInterfaceTypeElementEClass, COMPOSITE_INTERFACE_TYPE_ELEMENT__NAME);
    createEReference(compositeInterfaceTypeElementEClass, COMPOSITE_INTERFACE_TYPE_ELEMENT__TYPE);
    createEAttribute(compositeInterfaceTypeElementEClass, COMPOSITE_INTERFACE_TYPE_ELEMENT__DIRECTION);

    refInterfaceTypeElementEClass = createEClass(REF_INTERFACE_TYPE_ELEMENT);
    createEReference(refInterfaceTypeElementEClass, REF_INTERFACE_TYPE_ELEMENT__TYPE);

    atomInterfaceTypeEClass = createEClass(ATOM_INTERFACE_TYPE);
    createEReference(atomInterfaceTypeEClass, ATOM_INTERFACE_TYPE__ITEMS);

    compositeInterfaceTypeEClass = createEClass(COMPOSITE_INTERFACE_TYPE);
    createEReference(compositeInterfaceTypeEClass, COMPOSITE_INTERFACE_TYPE__ITEMS);

    refInterfaceTypeEClass = createEClass(REF_INTERFACE_TYPE);
    createEReference(refInterfaceTypeEClass, REF_INTERFACE_TYPE__ITEMS);

    lidlParameterEClass = createEClass(LIDL_PARAMETER);
    createEAttribute(lidlParameterEClass, LIDL_PARAMETER__NAME);
    createEReference(lidlParameterEClass, LIDL_PARAMETER__INTERFACE);

    lidlTextEClass = createEClass(LIDL_TEXT);
    createEAttribute(lidlTextEClass, LIDL_TEXT__TEXT);

    lidlCallExpressionEClass = createEClass(LIDL_CALL_EXPRESSION);

    textCallPartEClass = createEClass(TEXT_CALL_PART);
    createEAttribute(textCallPartEClass, TEXT_CALL_PART__TEXT);

    paramCallPartEClass = createEClass(PARAM_CALL_PART);
    createEReference(paramCallPartEClass, PARAM_CALL_PART__PARAM);

    lidlStringConstantEClass = createEClass(LIDL_STRING_CONSTANT);
    createEAttribute(lidlStringConstantEClass, LIDL_STRING_CONSTANT__VALUE);

    lidlNumberConstantEClass = createEClass(LIDL_NUMBER_CONSTANT);
    createEAttribute(lidlNumberConstantEClass, LIDL_NUMBER_CONSTANT__VALUE);

    lidlBoolConstantEClass = createEClass(LIDL_BOOL_CONSTANT);
    createEAttribute(lidlBoolConstantEClass, LIDL_BOOL_CONSTANT__VALUE);

    lidlAvtivationConstantEClass = createEClass(LIDL_AVTIVATION_CONSTANT);
    createEAttribute(lidlAvtivationConstantEClass, LIDL_AVTIVATION_CONSTANT__VALUE);

    lidlCompositionEClass = createEClass(LIDL_COMPOSITION);
    createEReference(lidlCompositionEClass, LIDL_COMPOSITION__BODY);

    // Create enums
    dataDirectionEEnum = createEEnum(DATA_DIRECTION);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    lidlDataEClass.getESuperTypes().add(this.getLidlDefinition());
    lidlInterfaceEClass.getESuperTypes().add(this.getLidlDefinition());
    interfaceElementEClass.getESuperTypes().add(this.getLidlSymbol());
    lidlInteractionEClass.getESuperTypes().add(this.getLidlDefinition());
    idPartEClass.getESuperTypes().add(this.getLidlSymbol());
    lidlExpressionEClass.getESuperTypes().add(this.getLidlExpresson());
    lidlCompositionElementEClass.getESuperTypes().add(this.getLidlSymbol());
    compositeDataTypeEClass.getESuperTypes().add(this.getLidlDataType());
    refDataTypeEClass.getESuperTypes().add(this.getLidlDataType());
    compositeDataTypeElementEClass.getESuperTypes().add(this.getTypeElement());
    refDataTypeElementEClass.getESuperTypes().add(this.getTypeElement());
    atomInterfaceTypeElementEClass.getESuperTypes().add(this.getInterfaceElement());
    compositeInterfaceTypeElementEClass.getESuperTypes().add(this.getInterfaceElement());
    refInterfaceTypeElementEClass.getESuperTypes().add(this.getInterfaceElement());
    atomInterfaceTypeEClass.getESuperTypes().add(this.getLidlInterfaceType());
    compositeInterfaceTypeEClass.getESuperTypes().add(this.getLidlInterfaceType());
    refInterfaceTypeEClass.getESuperTypes().add(this.getLidlInterfaceType());
    lidlParameterEClass.getESuperTypes().add(this.getIDPart());
    lidlTextEClass.getESuperTypes().add(this.getIDPart());
    lidlCallExpressionEClass.getESuperTypes().add(this.getLidlExpression());
    textCallPartEClass.getESuperTypes().add(this.getCallPart());
    paramCallPartEClass.getESuperTypes().add(this.getCallPart());
    lidlStringConstantEClass.getESuperTypes().add(this.getLidlExpression());
    lidlNumberConstantEClass.getESuperTypes().add(this.getLidlExpression());
    lidlBoolConstantEClass.getESuperTypes().add(this.getLidlExpression());
    lidlAvtivationConstantEClass.getESuperTypes().add(this.getLidlExpression());
    lidlCompositionEClass.getESuperTypes().add(this.getLidlExpression());

    // Initialize classes and features; add operations and parameters
    initEClass(lidlProgramEClass, LidlProgram.class, "LidlProgram", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlProgram_Pack(), ecorePackage.getEBoolean(), "pack", null, 0, 1, LidlProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLidlProgram_Name(), ecorePackage.getEString(), "name", null, 0, 1, LidlProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlProgram_Imports(), this.getLidlImport(), null, "imports", null, 0, -1, LidlProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlProgram_Definitions(), this.getLidlDefinition(), null, "definitions", null, 0, -1, LidlProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlImportEClass, LidlImport.class, "LidlImport", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlImport_ImportedNamespace(), ecorePackage.getEString(), "importedNamespace", null, 0, 1, LidlImport.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlDefinitionEClass, LidlDefinition.class, "LidlDefinition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlDefinition_Nested(), ecorePackage.getEBoolean(), "nested", null, 0, 1, LidlDefinition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlDataEClass, LidlData.class, "LidlData", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlData_Name(), ecorePackage.getEString(), "name", null, 0, 1, LidlData.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlData_NestedDef(), this.getLidlData(), null, "nestedDef", null, 0, -1, LidlData.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlData_Definition(), this.getLidlDataType(), null, "definition", null, 0, 1, LidlData.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLidlData_Defined(), ecorePackage.getEBoolean(), "defined", null, 0, 1, LidlData.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlDataTypeEClass, LidlDataType.class, "LidlDataType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLidlDataType_Items(), this.getTypeElement(), null, "items", null, 0, -1, LidlDataType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(typeElementEClass, TypeElement.class, "TypeElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTypeElement_IsArray(), ecorePackage.getEBoolean(), "isArray", null, 0, 1, TypeElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTypeElement_Type(), this.getLidlData(), null, "type", null, 0, 1, TypeElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlInterfaceEClass, LidlInterface.class, "LidlInterface", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlInterface_Name(), ecorePackage.getEString(), "name", null, 0, 1, LidlInterface.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlInterface_NestedDef(), this.getLidlInterface(), null, "nestedDef", null, 0, -1, LidlInterface.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlInterface_Definition(), this.getLidlInterfaceType(), null, "definition", null, 0, 1, LidlInterface.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLidlInterface_Defined(), ecorePackage.getEBoolean(), "defined", null, 0, 1, LidlInterface.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlInterfaceTypeEClass, LidlInterfaceType.class, "LidlInterfaceType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlInterfaceType_Conjugate(), ecorePackage.getEBoolean(), "conjugate", null, 0, 1, LidlInterfaceType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(interfaceElementEClass, InterfaceElement.class, "InterfaceElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(lidlInteractionEClass, LidlInteraction.class, "LidlInteraction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLidlInteraction_Id(), this.getLidlInteractionID(), null, "id", null, 0, 1, LidlInteraction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlInteraction_Interface(), this.getLidlInterfaceType(), null, "interface", null, 0, 1, LidlInteraction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlInteraction_NestedDef(), this.getLidlInteraction(), null, "nestedDef", null, 0, -1, LidlInteraction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlInteraction_Definition(), this.getLidlExpresson(), null, "definition", null, 0, 1, LidlInteraction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlInteractionIDEClass, LidlInteractionID.class, "LidlInteractionID", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLidlInteractionID_Items(), this.getIDPart(), null, "items", null, 0, -1, LidlInteractionID.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(idPartEClass, IDPart.class, "IDPart", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(lidlExpressonEClass, LidlExpresson.class, "LidlExpresson", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(lidlExpressionEClass, LidlExpression.class, "LidlExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLidlExpression_Item(), this.getLidlArrayItem(), null, "item", null, 0, -1, LidlExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlExpression_Items(), ecorePackage.getEObject(), null, "items", null, 0, -1, LidlExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(callPartEClass, CallPart.class, "CallPart", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(lidlArrayItemEClass, LidlArrayItem.class, "LidlArrayItem", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLidlArrayItem_Value(), this.getLidlExpresson(), null, "value", null, 0, 1, LidlArrayItem.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlSymbolEClass, LidlSymbol.class, "LidlSymbol", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(lidlCompositionElementEClass, LidlCompositionElement.class, "LidlCompositionElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlCompositionElement_Param(), ecorePackage.getEString(), "param", null, 0, 1, LidlCompositionElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlCompositionElement_Value(), this.getLidlExpresson(), null, "value", null, 0, 1, LidlCompositionElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(compositeDataTypeEClass, CompositeDataType.class, "CompositeDataType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(refDataTypeEClass, RefDataType.class, "RefDataType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(compositeDataTypeElementEClass, CompositeDataTypeElement.class, "CompositeDataTypeElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCompositeDataTypeElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, CompositeDataTypeElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(refDataTypeElementEClass, RefDataTypeElement.class, "RefDataTypeElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(atomInterfaceTypeElementEClass, AtomInterfaceTypeElement.class, "AtomInterfaceTypeElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAtomInterfaceTypeElement_Type(), this.getLidlData(), null, "type", null, 0, 1, AtomInterfaceTypeElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAtomInterfaceTypeElement_Direction(), this.getDataDirection(), "direction", null, 0, 1, AtomInterfaceTypeElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(compositeInterfaceTypeElementEClass, CompositeInterfaceTypeElement.class, "CompositeInterfaceTypeElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCompositeInterfaceTypeElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, CompositeInterfaceTypeElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCompositeInterfaceTypeElement_Type(), this.getLidlDefinition(), null, "type", null, 0, 1, CompositeInterfaceTypeElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCompositeInterfaceTypeElement_Direction(), this.getDataDirection(), "direction", null, 0, 1, CompositeInterfaceTypeElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(refInterfaceTypeElementEClass, RefInterfaceTypeElement.class, "RefInterfaceTypeElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRefInterfaceTypeElement_Type(), this.getLidlInterface(), null, "type", null, 0, 1, RefInterfaceTypeElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(atomInterfaceTypeEClass, AtomInterfaceType.class, "AtomInterfaceType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAtomInterfaceType_Items(), this.getInterfaceElement(), null, "items", null, 0, 1, AtomInterfaceType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(compositeInterfaceTypeEClass, CompositeInterfaceType.class, "CompositeInterfaceType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCompositeInterfaceType_Items(), this.getInterfaceElement(), null, "items", null, 0, -1, CompositeInterfaceType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(refInterfaceTypeEClass, RefInterfaceType.class, "RefInterfaceType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRefInterfaceType_Items(), this.getInterfaceElement(), null, "items", null, 0, 1, RefInterfaceType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlParameterEClass, LidlParameter.class, "LidlParameter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlParameter_Name(), ecorePackage.getEString(), "name", null, 0, 1, LidlParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLidlParameter_Interface(), this.getLidlInterfaceType(), null, "interface", null, 0, 1, LidlParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlTextEClass, LidlText.class, "LidlText", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlText_Text(), ecorePackage.getEString(), "text", null, 0, 1, LidlText.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlCallExpressionEClass, LidlCallExpression.class, "LidlCallExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(textCallPartEClass, TextCallPart.class, "TextCallPart", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTextCallPart_Text(), ecorePackage.getEString(), "text", null, 0, 1, TextCallPart.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(paramCallPartEClass, ParamCallPart.class, "ParamCallPart", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getParamCallPart_Param(), this.getLidlExpresson(), null, "param", null, 0, 1, ParamCallPart.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlStringConstantEClass, LidlStringConstant.class, "LidlStringConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlStringConstant_Value(), ecorePackage.getEString(), "value", null, 0, 1, LidlStringConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlNumberConstantEClass, LidlNumberConstant.class, "LidlNumberConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlNumberConstant_Value(), ecorePackage.getEString(), "value", null, 0, 1, LidlNumberConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlBoolConstantEClass, LidlBoolConstant.class, "LidlBoolConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlBoolConstant_Value(), ecorePackage.getEString(), "value", null, 0, 1, LidlBoolConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlAvtivationConstantEClass, LidlAvtivationConstant.class, "LidlAvtivationConstant", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLidlAvtivationConstant_Value(), ecorePackage.getEString(), "value", null, 0, 1, LidlAvtivationConstant.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(lidlCompositionEClass, LidlComposition.class, "LidlComposition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLidlComposition_Body(), this.getLidlExpression(), null, "body", null, 0, 1, LidlComposition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(dataDirectionEEnum, DataDirection.class, "DataDirection");
    addEEnumLiteral(dataDirectionEEnum, DataDirection.IN);
    addEEnumLiteral(dataDirectionEEnum, DataDirection.OUT);

    // Create resource
    createResource(eNS_URI);
  }

} //LidlPackageImpl
