/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl.impl;

import java.util.Collection;

import lab.buaa.software.lidl.lidl.LidlData;
import lab.buaa.software.lidl.lidl.LidlDataType;
import lab.buaa.software.lidl.lidl.LidlPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link lab.buaa.software.lidl.lidl.impl.LidlDataImpl#getName <em>Name</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.impl.LidlDataImpl#getNestedDef <em>Nested Def</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.impl.LidlDataImpl#getDefinition <em>Definition</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.impl.LidlDataImpl#isDefined <em>Defined</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LidlDataImpl extends LidlDefinitionImpl implements LidlData
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getNestedDef() <em>Nested Def</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNestedDef()
   * @generated
   * @ordered
   */
  protected EList<LidlData> nestedDef;

  /**
   * The cached value of the '{@link #getDefinition() <em>Definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefinition()
   * @generated
   * @ordered
   */
  protected LidlDataType definition;

  /**
   * The default value of the '{@link #isDefined() <em>Defined</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isDefined()
   * @generated
   * @ordered
   */
  protected static final boolean DEFINED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isDefined() <em>Defined</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isDefined()
   * @generated
   * @ordered
   */
  protected boolean defined = DEFINED_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LidlDataImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LidlPackage.Literals.LIDL_DATA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LidlPackage.LIDL_DATA__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LidlData> getNestedDef()
  {
    if (nestedDef == null)
    {
      nestedDef = new EObjectContainmentEList<LidlData>(LidlData.class, this, LidlPackage.LIDL_DATA__NESTED_DEF);
    }
    return nestedDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LidlDataType getDefinition()
  {
    return definition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDefinition(LidlDataType newDefinition, NotificationChain msgs)
  {
    LidlDataType oldDefinition = definition;
    definition = newDefinition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LidlPackage.LIDL_DATA__DEFINITION, oldDefinition, newDefinition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefinition(LidlDataType newDefinition)
  {
    if (newDefinition != definition)
    {
      NotificationChain msgs = null;
      if (definition != null)
        msgs = ((InternalEObject)definition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LidlPackage.LIDL_DATA__DEFINITION, null, msgs);
      if (newDefinition != null)
        msgs = ((InternalEObject)newDefinition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LidlPackage.LIDL_DATA__DEFINITION, null, msgs);
      msgs = basicSetDefinition(newDefinition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LidlPackage.LIDL_DATA__DEFINITION, newDefinition, newDefinition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isDefined()
  {
    return defined;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefined(boolean newDefined)
  {
    boolean oldDefined = defined;
    defined = newDefined;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LidlPackage.LIDL_DATA__DEFINED, oldDefined, defined));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LidlPackage.LIDL_DATA__NESTED_DEF:
        return ((InternalEList<?>)getNestedDef()).basicRemove(otherEnd, msgs);
      case LidlPackage.LIDL_DATA__DEFINITION:
        return basicSetDefinition(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LidlPackage.LIDL_DATA__NAME:
        return getName();
      case LidlPackage.LIDL_DATA__NESTED_DEF:
        return getNestedDef();
      case LidlPackage.LIDL_DATA__DEFINITION:
        return getDefinition();
      case LidlPackage.LIDL_DATA__DEFINED:
        return isDefined();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LidlPackage.LIDL_DATA__NAME:
        setName((String)newValue);
        return;
      case LidlPackage.LIDL_DATA__NESTED_DEF:
        getNestedDef().clear();
        getNestedDef().addAll((Collection<? extends LidlData>)newValue);
        return;
      case LidlPackage.LIDL_DATA__DEFINITION:
        setDefinition((LidlDataType)newValue);
        return;
      case LidlPackage.LIDL_DATA__DEFINED:
        setDefined((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LidlPackage.LIDL_DATA__NAME:
        setName(NAME_EDEFAULT);
        return;
      case LidlPackage.LIDL_DATA__NESTED_DEF:
        getNestedDef().clear();
        return;
      case LidlPackage.LIDL_DATA__DEFINITION:
        setDefinition((LidlDataType)null);
        return;
      case LidlPackage.LIDL_DATA__DEFINED:
        setDefined(DEFINED_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LidlPackage.LIDL_DATA__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case LidlPackage.LIDL_DATA__NESTED_DEF:
        return nestedDef != null && !nestedDef.isEmpty();
      case LidlPackage.LIDL_DATA__DEFINITION:
        return definition != null;
      case LidlPackage.LIDL_DATA__DEFINED:
        return defined != DEFINED_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", defined: ");
    result.append(defined);
    result.append(')');
    return result.toString();
  }

} //LidlDataImpl
