/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl.impl;

import lab.buaa.software.lidl.lidl.LidlPackage;
import lab.buaa.software.lidl.lidl.RefDataTypeElement;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ref Data Type Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RefDataTypeElementImpl extends TypeElementImpl implements RefDataTypeElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RefDataTypeElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LidlPackage.Literals.REF_DATA_TYPE_ELEMENT;
  }

} //RefDataTypeElementImpl
