/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class LidlIdeModule extends AbstractLidlIdeModule {
}
