/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import lab.buaa.software.lidl.LidlRuntimeModule;
import lab.buaa.software.lidl.LidlStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class LidlIdeSetup extends LidlStandaloneSetup {
  @Override
  public Injector createInjector() {
    LidlRuntimeModule _lidlRuntimeModule = new LidlRuntimeModule();
    LidlIdeModule _lidlIdeModule = new LidlIdeModule();
    return Guice.createInjector(Modules2.mixin(_lidlRuntimeModule, _lidlIdeModule));
  }
}
