/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Part</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getCallPart()
 * @model
 * @generated
 */
public interface CallPart extends EObject
{
} // CallPart
