/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Composite Interface Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lab.buaa.software.lidl.lidl.CompositeInterfaceType#getItems <em>Items</em>}</li>
 * </ul>
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getCompositeInterfaceType()
 * @model
 * @generated
 */
public interface CompositeInterfaceType extends LidlInterfaceType
{
  /**
   * Returns the value of the '<em><b>Items</b></em>' containment reference list.
   * The list contents are of type {@link lab.buaa.software.lidl.lidl.InterfaceElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' containment reference list.
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getCompositeInterfaceType_Items()
   * @model containment="true"
   * @generated
   */
  EList<InterfaceElement> getItems();

} // CompositeInterfaceType
