/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Composite Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getCompositeDataType()
 * @model
 * @generated
 */
public interface CompositeDataType extends LidlDataType
{
} // CompositeDataType
