/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Composite Interface Type Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lab.buaa.software.lidl.lidl.CompositeInterfaceTypeElement#getName <em>Name</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.CompositeInterfaceTypeElement#getType <em>Type</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.CompositeInterfaceTypeElement#getDirection <em>Direction</em>}</li>
 * </ul>
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getCompositeInterfaceTypeElement()
 * @model
 * @generated
 */
public interface CompositeInterfaceTypeElement extends InterfaceElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getCompositeInterfaceTypeElement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.CompositeInterfaceTypeElement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(LidlDefinition)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getCompositeInterfaceTypeElement_Type()
   * @model
   * @generated
   */
  LidlDefinition getType();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.CompositeInterfaceTypeElement#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(LidlDefinition value);

  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * The literals are from the enumeration {@link lab.buaa.software.lidl.lidl.DataDirection}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see lab.buaa.software.lidl.lidl.DataDirection
   * @see #setDirection(DataDirection)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getCompositeInterfaceTypeElement_Direction()
   * @model
   * @generated
   */
  DataDirection getDirection();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.CompositeInterfaceTypeElement#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see lab.buaa.software.lidl.lidl.DataDirection
   * @see #getDirection()
   * @generated
   */
  void setDirection(DataDirection value);

} // CompositeInterfaceTypeElement
