/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interface Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getInterfaceElement()
 * @model
 * @generated
 */
public interface InterfaceElement extends LidlSymbol
{
} // InterfaceElement
