/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlInteraction#getId <em>Id</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlInteraction#getInterface <em>Interface</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlInteraction#getNestedDef <em>Nested Def</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlInteraction#getDefinition <em>Definition</em>}</li>
 * </ul>
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlInteraction()
 * @model
 * @generated
 */
public interface LidlInteraction extends LidlDefinition
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' containment reference.
   * @see #setId(LidlInteractionID)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlInteraction_Id()
   * @model containment="true"
   * @generated
   */
  LidlInteractionID getId();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.LidlInteraction#getId <em>Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' containment reference.
   * @see #getId()
   * @generated
   */
  void setId(LidlInteractionID value);

  /**
   * Returns the value of the '<em><b>Interface</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interface</em>' containment reference.
   * @see #setInterface(LidlInterfaceType)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlInteraction_Interface()
   * @model containment="true"
   * @generated
   */
  LidlInterfaceType getInterface();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.LidlInteraction#getInterface <em>Interface</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interface</em>' containment reference.
   * @see #getInterface()
   * @generated
   */
  void setInterface(LidlInterfaceType value);

  /**
   * Returns the value of the '<em><b>Nested Def</b></em>' containment reference list.
   * The list contents are of type {@link lab.buaa.software.lidl.lidl.LidlInteraction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nested Def</em>' containment reference list.
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlInteraction_NestedDef()
   * @model containment="true"
   * @generated
   */
  EList<LidlInteraction> getNestedDef();

  /**
   * Returns the value of the '<em><b>Definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definition</em>' containment reference.
   * @see #setDefinition(LidlExpresson)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlInteraction_Definition()
   * @model containment="true"
   * @generated
   */
  LidlExpresson getDefinition();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.LidlInteraction#getDefinition <em>Definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Definition</em>' containment reference.
   * @see #getDefinition()
   * @generated
   */
  void setDefinition(LidlExpresson value);

} // LidlInteraction
