/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlDefinition#isNested <em>Nested</em>}</li>
 * </ul>
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlDefinition()
 * @model
 * @generated
 */
public interface LidlDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Nested</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nested</em>' attribute.
   * @see #setNested(boolean)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlDefinition_Nested()
   * @model
   * @generated
   */
  boolean isNested();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.LidlDefinition#isNested <em>Nested</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nested</em>' attribute.
   * @see #isNested()
   * @generated
   */
  void setNested(boolean value);

} // LidlDefinition
