/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interface Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlInterfaceType#isConjugate <em>Conjugate</em>}</li>
 * </ul>
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlInterfaceType()
 * @model
 * @generated
 */
public interface LidlInterfaceType extends EObject
{
  /**
   * Returns the value of the '<em><b>Conjugate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conjugate</em>' attribute.
   * @see #setConjugate(boolean)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlInterfaceType_Conjugate()
   * @model
   * @generated
   */
  boolean isConjugate();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.LidlInterfaceType#isConjugate <em>Conjugate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conjugate</em>' attribute.
   * @see #isConjugate()
   * @generated
   */
  void setConjugate(boolean value);

} // LidlInterfaceType
