/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlCallExpression()
 * @model
 * @generated
 */
public interface LidlCallExpression extends LidlExpression
{
} // LidlCallExpression
