/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlProgram#isPack <em>Pack</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlProgram#getName <em>Name</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlProgram#getImports <em>Imports</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlProgram#getDefinitions <em>Definitions</em>}</li>
 * </ul>
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlProgram()
 * @model
 * @generated
 */
public interface LidlProgram extends EObject
{
  /**
   * Returns the value of the '<em><b>Pack</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pack</em>' attribute.
   * @see #setPack(boolean)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlProgram_Pack()
   * @model
   * @generated
   */
  boolean isPack();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.LidlProgram#isPack <em>Pack</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pack</em>' attribute.
   * @see #isPack()
   * @generated
   */
  void setPack(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlProgram_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.LidlProgram#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link lab.buaa.software.lidl.lidl.LidlImport}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlProgram_Imports()
   * @model containment="true"
   * @generated
   */
  EList<LidlImport> getImports();

  /**
   * Returns the value of the '<em><b>Definitions</b></em>' containment reference list.
   * The list contents are of type {@link lab.buaa.software.lidl.lidl.LidlDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definitions</em>' containment reference list.
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlProgram_Definitions()
   * @model containment="true"
   * @generated
   */
  EList<LidlDefinition> getDefinitions();

} // LidlProgram
