/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlExpression#getItem <em>Item</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlExpression#getItems <em>Items</em>}</li>
 * </ul>
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlExpression()
 * @model
 * @generated
 */
public interface LidlExpression extends LidlExpresson
{
  /**
   * Returns the value of the '<em><b>Item</b></em>' containment reference list.
   * The list contents are of type {@link lab.buaa.software.lidl.lidl.LidlArrayItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Item</em>' containment reference list.
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlExpression_Item()
   * @model containment="true"
   * @generated
   */
  EList<LidlArrayItem> getItem();

  /**
   * Returns the value of the '<em><b>Items</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' containment reference list.
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlExpression_Items()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getItems();

} // LidlExpression
