/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlParameter#getName <em>Name</em>}</li>
 *   <li>{@link lab.buaa.software.lidl.lidl.LidlParameter#getInterface <em>Interface</em>}</li>
 * </ul>
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlParameter()
 * @model
 * @generated
 */
public interface LidlParameter extends IDPart
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlParameter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.LidlParameter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Interface</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interface</em>' containment reference.
   * @see #setInterface(LidlInterfaceType)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getLidlParameter_Interface()
   * @model containment="true"
   * @generated
   */
  LidlInterfaceType getInterface();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.LidlParameter#getInterface <em>Interface</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interface</em>' containment reference.
   * @see #getInterface()
   * @generated
   */
  void setInterface(LidlInterfaceType value);

} // LidlParameter
