/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref Data Type Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getRefDataTypeElement()
 * @model
 * @generated
 */
public interface RefDataTypeElement extends TypeElement
{
} // RefDataTypeElement
