/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref Interface Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lab.buaa.software.lidl.lidl.RefInterfaceType#getItems <em>Items</em>}</li>
 * </ul>
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getRefInterfaceType()
 * @model
 * @generated
 */
public interface RefInterfaceType extends LidlInterfaceType
{
  /**
   * Returns the value of the '<em><b>Items</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' containment reference.
   * @see #setItems(InterfaceElement)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getRefInterfaceType_Items()
   * @model containment="true"
   * @generated
   */
  InterfaceElement getItems();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.RefInterfaceType#getItems <em>Items</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Items</em>' containment reference.
   * @see #getItems()
   * @generated
   */
  void setItems(InterfaceElement value);

} // RefInterfaceType
