/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.lidl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref Interface Type Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lab.buaa.software.lidl.lidl.RefInterfaceTypeElement#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see lab.buaa.software.lidl.lidl.LidlPackage#getRefInterfaceTypeElement()
 * @model
 * @generated
 */
public interface RefInterfaceTypeElement extends InterfaceElement
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(LidlInterface)
   * @see lab.buaa.software.lidl.lidl.LidlPackage#getRefInterfaceTypeElement_Type()
   * @model
   * @generated
   */
  LidlInterface getType();

  /**
   * Sets the value of the '{@link lab.buaa.software.lidl.lidl.RefInterfaceTypeElement#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(LidlInterface value);

} // RefInterfaceTypeElement
