/*
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.ui.tests;

import com.google.inject.Injector;
import lab.buaa.software.lidl.ui.internal.LidlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LidlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LidlActivator.getInstance().getInjector("lab.buaa.software.lidl.Lidl");
	}

}
