/*
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLidlScopeProvider extends DelegatingScopeProvider {
}
