/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.ui.labeling;

import com.google.inject.Inject;
import lab.buaa.software.lidl.lidl.CompositeDataTypeElement;
import lab.buaa.software.lidl.lidl.LidlData;
import lab.buaa.software.lidl.lidl.RefDataTypeElement;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class LidlLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public LidlLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final LidlData d) {
    String _name = d.getName();
    return (_name + "");
  }
  
  public String text(final CompositeDataTypeElement cdte) {
    String _name = cdte.getName();
    String _plus = (_name + " : ");
    String _name_1 = cdte.getType().getName();
    return (_plus + _name_1);
  }
  
  public String text(final RefDataTypeElement rdte) {
    String _name = rdte.getType().getName();
    return (_name + "");
  }
}
