/*
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLidlValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(lab.buaa.software.lidl.lidl.LidlPackage.eINSTANCE);
		return result;
	}
}
