/*
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl.ui;

import com.google.inject.Injector;
import lab.buaa.software.lidl.ui.internal.LidlActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LidlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LidlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LidlActivator activator = LidlActivator.getInstance();
		return activator != null ? activator.getInjector(LidlActivator.LAB_BUAA_SOFTWARE_LIDL_LIDL) : null;
	}

}
