/**
 * generated by Xtext 2.25.0
 */
package lab.buaa.software.lidl;

import com.google.inject.Binder;
import com.google.inject.name.Names;
import lab.buaa.software.lidl.scoping.LidlImportedNamespaceAwareLocalScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class LidlRuntimeModule extends AbstractLidlRuntimeModule {
  @Override
  public void configureIScopeProviderDelegate(final Binder binder) {
    binder.<IScopeProvider>bind(IScopeProvider.class).annotatedWith(
      Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(
      LidlImportedNamespaceAwareLocalScopeProvider.class);
  }
}
